### PR TITLE
Move from Github Wiki on e-mission-server to e-mission-docs

### PR DESCRIPTION
**Pull request by brianmickel**
- created folder docs/e-mission-server
- created one file for each wiki page with content copypasted
- created main.md with contents of e-mission-server readme.md
- added title as h1 to each file

### CODE REVIEW

**Comment by shankari** [comment]
@brianmickel Looks good overall.
I am not sure whether the README should be moved into docs, or whether it should stay in the server repository.

Most github repositories have a README that is specific to them, and we can link to the README from the documentation repositories.
Thoughts?

**Comment by brianmickel** [comment]
@shankari I agree completely. removed with the most recent commit

**Comment by shankari** [comment]
Removed the "Wiki" tab from the e-mission-server repo to avoid confusing people
The Wiki isn't deleted - it can be restored by re-enabling the tab, which is good for now.
Eventually, as it gets more obsolete, I would like to delete it completely, but don't want to mess with figuring out how to do that at this time.

**Comment by shankari** [comment]
@brianmickel if you do something similar for the e-mission-phone wiki too, all the documentation will be centralized in one place. No rush, but that would be pretty good!

**Pull request merged**
