### PR TITLE
a new readme for docs

### PR DESCRIPTION
**Pull request by PatGendre**
as discussed yesterday, a proposal for a more complete summary entry page in the readme (all pages in the current docs are referenced here).
this can help prepare HTML generated doc site e.g. with readthedocs

### CODE REVIEW

**Comment by shankari** [comment]
Not sure that the RTD actually works yet, but let's merge and figure it out.

**Comment by PatGendre** [comment]
@shankari thanks! FYI I created a branch on our doc repo to try out moving the .MD files in a directory tree more in line with the summary proposed in the README
https://github.com/fabmob/e-mission-docs/tree/reorg
On readthedocs there is a problem with the upper menu but I did not configure anything and used the default settings. It looks like this:
https://fabmob.readthedocs.io/en/latest/

**Comment by shankari** [comment]
wow! that does look pretty cool. I don't have time to investigate how to set up the menu on RTD. I am happy to merge the restructuring whenever you are ready, it is already better than what we have now. I am a big believer that we shouldn't let the perfect be the enemy of the good 😄

**Comment by PatGendre** [comment]
Hi @shankari 
I have improved the pages generated from RDT https://fabmob.readthedocs.io/en/latest/
from our reorg branch https://github.com/fabmob/e-mission-docs/tree/reorg
For the moment in this repo I did not delete nor modify any MD file (except the README), just moved them in other directories.
There is still a relative path problem and the images are not displayed, but as I say also often (in the French version) "the better is the enemy of the good" ;-) Moreover, this will imply to modify slight the MD files so this is the kind of corrections that'd better done afterwards.

Tell me if this Ok, then I can submit a PR to the e-mission-docs repo?

**Comment by shankari** [comment]
@PatGendre this looks great. If you submit a PR, I will merge 😄

**Pull request merged**
