### PR TITLE
some updates from fabmob docs: notice about miniconda versions + update RP setup + curr_run_ts=... error + links to videos

### PR DESCRIPTION
**Pull request by PatGendre**
when I reinstalled e-mission-server on my PC, I couldn't setup the emission env with the latest miniconda version so I tried an older 4.4.10 version and this worked. I suppose this can also happen with anaconda. So I added a small notice in the install page.

### CODE REVIEW

**Comment by PatGendre** [comment]
Hi
I add a few lines with links to the 4 UI videos in the README, I hope it is more or less what you intended to add to the e-mission docs homepage.

**Comment by shankari** [comment]
@PatGendre When uploaded to, the vidoes don't for me because they are too big. Do they work for you? I am going to use nextcloud for now and you can fix after you test.

**Comment by PatGendre** [comment]
> @PatGendre When uploaded to, the vidoes don't for me because they are too big. Do they work for you? I am going to use the nextcloud links for now and you can fix after you test.

Hi @shankari, yes the video work at least on https://github.com/fabmob/e-mission-docs/tree/e-mission-contrib , I have not tested on readthedocs.

**Comment by shankari** [comment]
@PatGendre the videos work on https://github.com/fabmob/e-mission-docs/tree/e-mission-contrib because I changed them to nextcloud links. Try changing them back to github links and see if they work.

**Comment by PatGendre** [comment]
@shankari ok, no the github links don't work. I suppose that's why I pointed to the nextcloud links even if not in the e-mission-docs repo.

**Comment by shankari** [comment]
Actually, the links were to github. I replaced them with nextcloud before the merge since you had given me (the maintainer) permission to edit the documents.
https://github.com/e-mission/e-mission-docs/pull/460/commits/95c509be82ef78614d07f2f75e1320ca39fe7250

Let's just leave them as nextcloud right now.

**Comment by PatGendre** [comment]
Ok, fine, thank you:-) I don't remember what I did, I suppose the idea was to put all resources in github but it was not a good idea.

**Pull request merged**
