### PR TITLE
Add comparative evaluation

### PR DESCRIPTION
**Pull request by shankari**
Thanks to @PatGendre

### CODE REVIEW

**Comment by shankari** [comment]
@jf87 @PatGendre @stephhuerre I changed the README to add a comparative eval because it looks like a lot of websites have it. Is this useful? Or should I just say that we are are the first and soon to be only open source platform and put the comparisons into another document?

**Comment by shankari** [comment]
It's hard to review markdown in a PR, so try 
https://github.com/e-mission/e-mission-docs/tree/add-comparitive-eval to see it with formatting.

**Comment by PatGendre** [comment]
@shankari thank you, yes the review it can be useful as an argument for e-mission in the README,
of course the review is far for exhaustive so maybe we'll discover other interesting SDKs and may be open software, too!

**Comment by PatGendre** [comment]
PS moprim is an SDK but there is non public doc, radar.io is american (NYC based I think)

**Comment by shankari** [comment]
>  of course the review is far for exhaustive so maybe we'll discover other interesting SDKs and may be open software, too!

I think we already found something interesting - the LocoKit effort. I plan to reach out to them once this craziness dies down to see if they want to merge too.

**Pull request merged**
